"""initial schema

Revision ID: 5c5bc2d55945
Revises: 
Create Date: 2026-03-13 02:06:39.035563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c5bc2d55945'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('elections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=True),
    sa.Column('election_type', sa.String(length=100), nullable=False),
    sa.Column('territory', sa.String(length=200), nullable=True),
    sa.Column('tse_election_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_elections_year'), 'elections', ['year'], unique=False)
    op.create_table('institutional_contexts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('validity', postgresql.TSTZRANGE(), nullable=False),
    sa.Column('regime_name', sa.String(length=200), nullable=False),
    sa.Column('regime_type', sa.String(length=100), nullable=True),
    sa.Column('constitution', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('institution', sa.String(length=200), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=True),
    sa.Column('territory_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('abbreviation', sa.String(length=30), nullable=False),
    sa.Column('founded_date', sa.Date(), nullable=True),
    sa.Column('dissolved_date', sa.Date(), nullable=True),
    sa.Column('tse_code', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parties_abbreviation'), 'parties', ['abbreviation'], unique=False)
    op.create_table('people',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_name', sa.String(length=300), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('death_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('bio_summary', sa.Text(), nullable=True),
    sa.Column('cpdoc_id', sa.String(length=100), nullable=True),
    sa.Column('tse_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpdoc_id'),
    sa.UniqueConstraint('tse_id')
    )
    op.create_index(op.f('ix_people_canonical_name'), 'people', ['canonical_name'], unique=False)
    op.create_table('candidacies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('election_id', sa.UUID(), nullable=False),
    sa.Column('office_id', sa.UUID(), nullable=True),
    sa.Column('party_id', sa.UUID(), nullable=True),
    sa.Column('territory', sa.String(length=200), nullable=True),
    sa.Column('result', sa.String(length=30), nullable=True),
    sa.Column('vote_count', sa.Integer(), nullable=True),
    sa.Column('validity', postgresql.TSTZRANGE(), nullable=True),
    sa.Column('source_label', sa.String(length=200), nullable=True),
    sa.Column('confidence', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidacies_person_id'), 'candidacies', ['person_id'], unique=False)
    op.create_table('mandates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('office_id', sa.UUID(), nullable=True),
    sa.Column('territory', sa.String(length=200), nullable=True),
    sa.Column('validity', postgresql.TSTZRANGE(), nullable=False),
    sa.Column('date_precision', sa.String(length=20), nullable=True),
    sa.Column('is_approximate', sa.Boolean(), nullable=True),
    sa.Column('interrupted', sa.Boolean(), nullable=True),
    sa.Column('interruption_reason', sa.String(length=100), nullable=True),
    sa.Column('source_label', sa.String(length=200), nullable=True),
    sa.Column('confidence', sa.String(length=10), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mandates_person_id'), 'mandates', ['person_id'], unique=False)
    op.create_table('party_affiliations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('party_id', sa.UUID(), nullable=False),
    sa.Column('validity', postgresql.TSTZRANGE(), nullable=False),
    sa.Column('date_precision', sa.String(length=20), nullable=True),
    sa.Column('is_approximate', sa.Boolean(), nullable=True),
    sa.Column('source_label', sa.String(length=200), nullable=True),
    sa.Column('confidence', sa.String(length=10), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_party_affiliations_party_id'), 'party_affiliations', ['party_id'], unique=False)
    op.create_index(op.f('ix_party_affiliations_person_id'), 'party_affiliations', ['person_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_party_affiliations_person_id'), table_name='party_affiliations')
    op.drop_index(op.f('ix_party_affiliations_party_id'), table_name='party_affiliations')
    op.drop_table('party_affiliations')
    op.drop_index(op.f('ix_mandates_person_id'), table_name='mandates')
    op.drop_table('mandates')
    op.drop_index(op.f('ix_candidacies_person_id'), table_name='candidacies')
    op.drop_table('candidacies')
    op.drop_index(op.f('ix_people_canonical_name'), table_name='people')
    op.drop_table('people')
    op.drop_index(op.f('ix_parties_abbreviation'), table_name='parties')
    op.drop_table('parties')
    op.drop_table('offices')
    op.drop_table('institutional_contexts')
    op.drop_index(op.f('ix_elections_year'), table_name='elections')
    op.drop_table('elections')
    # ### end Alembic commands ###
