"""add_people_name_birthdate_unique_index

Revision ID: a328b488b5b4
Revises: b9744991aacd
Create Date: 2026-03-16 04:25:14.444205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a328b488b5b4'
down_revision: Union[str, Sequence[str], None] = 'b9744991aacd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_people_name_birthdate', 'people', [sa.literal_column('immutable_unaccent(canonical_name)'), 'birth_date'], unique=True, postgresql_where=sa.text('birth_date IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_people_name_birthdate', table_name='people', postgresql_where=sa.text('birth_date IS NOT NULL'))
    # ### end Alembic commands ###
