"""add_people_external_ids_drop_tse_id

Revision ID: b9744991aacd
Revises: 25d5bc92fd1a
Create Date: 2026-03-16 04:10:08.530910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9744991aacd'
down_revision: Union[str, Sequence[str], None] = '25d5bc92fd1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people_external_ids',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_people_external_ids_source_external_id')
    )
    op.create_index(op.f('ix_people_external_ids_person_id'), 'people_external_ids', ['person_id'], unique=False)
    op.create_index(op.f('ix_candidacies_person_id'), 'candidacies', ['person_id'], unique=False)
    op.create_index(op.f('ix_elections_year'), 'elections', ['year'], unique=False)
    op.create_index(op.f('ix_mandates_person_id'), 'mandates', ['person_id'], unique=False)
    op.create_index(op.f('ix_parties_abbreviation'), 'parties', ['abbreviation'], unique=False)
    op.create_index(op.f('ix_party_affiliations_party_id'), 'party_affiliations', ['party_id'], unique=False)
    op.create_index(op.f('ix_party_affiliations_person_id'), 'party_affiliations', ['person_id'], unique=False)
    op.drop_index(op.f('ix_people_canonical_name_unaccent'), table_name='people')
    op.drop_constraint(op.f('people_tse_id_key'), 'people', type_='unique')
    op.drop_column('people', 'tse_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('tse_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('people_tse_id_key'), 'people', ['tse_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_people_canonical_name_unaccent'), 'people', [sa.literal_column('immutable_unaccent(canonical_name::text)')], unique=False)
    op.drop_index(op.f('ix_party_affiliations_person_id'), table_name='party_affiliations')
    op.drop_index(op.f('ix_party_affiliations_party_id'), table_name='party_affiliations')
    op.drop_index(op.f('ix_parties_abbreviation'), table_name='parties')
    op.drop_index(op.f('ix_mandates_person_id'), table_name='mandates')
    op.drop_index(op.f('ix_elections_year'), table_name='elections')
    op.drop_index(op.f('ix_candidacies_person_id'), table_name='candidacies')
    op.drop_index(op.f('ix_people_external_ids_person_id'), table_name='people_external_ids')
    op.drop_table('people_external_ids')
    # ### end Alembic commands ###
